### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Andrew1481432** [rtm516/GeyserAndroid#1]
2020-07-21 17:48:01.952 30730-31332/org.geysermc.app.android E/RakNetServer: An exception occurred in RakNet
    java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:83)
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:276)
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307)

**Comment by rtm516** [comment]
Yes, this project is in development and is nowhere near ready to be in use. When it is there will be an announcement in the Geyser discord
